/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\my\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-bc09bd4c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bc09bd4c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-3fdbf9de",
    path: "/components/%E5%B7%A6%E5%8F%B3%E6%8B%89%E5%8A%A8%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fdbf9de").then(next)
    },
  },
  {
    path: "/components/左右拉动组件.html",
    redirect: "/components/%E5%B7%A6%E5%8F%B3%E6%8B%89%E5%8A%A8%E7%BB%84%E4%BB%B6.html"
  },
  {
    path: "/components/左右拉动组件.html",
    redirect: "/components/%E5%B7%A6%E5%8F%B3%E6%8B%89%E5%8A%A8%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-609aeb54",
    path: "/posts/ES6%20%E5%B8%B8%E7%94%A8%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-609aeb54").then(next)
    },
  },
  {
    path: "/posts/ES6 常用语法.html",
    redirect: "/posts/ES6%20%E5%B8%B8%E7%94%A8%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/posts/ES6 常用语法.html",
    redirect: "/posts/ES6%20%E5%B8%B8%E7%94%A8%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-98bb5b48",
    path: "/posts/121501.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-98bb5b48").then(next)
    },
  },
  {
    name: "v-16132974",
    path: "/posts/ajax%E8%BF%94%E5%9B%9Eblob%E5%B0%81%E8%A3%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16132974").then(next)
    },
  },
  {
    path: "/posts/ajax返回blob封装.html",
    redirect: "/posts/ajax%E8%BF%94%E5%9B%9Eblob%E5%B0%81%E8%A3%85.html"
  },
  {
    path: "/posts/ajax返回blob封装.html",
    redirect: "/posts/ajax%E8%BF%94%E5%9B%9Eblob%E5%B0%81%E8%A3%85.html"
  },
  {
    name: "v-c069814e",
    path: "/posts/footer%E4%BD%8D%E7%BD%AE%E7%9A%84%E8%87%AA%E5%8A%A8%E9%80%82%E9%85%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c069814e").then(next)
    },
  },
  {
    path: "/posts/footer位置的自动适配.html",
    redirect: "/posts/footer%E4%BD%8D%E7%BD%AE%E7%9A%84%E8%87%AA%E5%8A%A8%E9%80%82%E9%85%8D.html"
  },
  {
    path: "/posts/footer位置的自动适配.html",
    redirect: "/posts/footer%E4%BD%8D%E7%BD%AE%E7%9A%84%E8%87%AA%E5%8A%A8%E9%80%82%E9%85%8D.html"
  },
  {
    name: "v-0a1dfd74",
    path: "/posts/uniapp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a1dfd74").then(next)
    },
  },
  {
    name: "v-7ab37238",
    path: "/posts/space-around%E6%9C%80%E5%90%8E%E4%B8%80%E8%A1%8C%E4%B8%8D%E8%83%BD%E5%B7%A6%E5%AF%B9%E9%BD%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ab37238").then(next)
    },
  },
  {
    path: "/posts/space-around最后一行不能左对齐.html",
    redirect: "/posts/space-around%E6%9C%80%E5%90%8E%E4%B8%80%E8%A1%8C%E4%B8%8D%E8%83%BD%E5%B7%A6%E5%AF%B9%E9%BD%90.html"
  },
  {
    path: "/posts/space-around最后一行不能左对齐.html",
    redirect: "/posts/space-around%E6%9C%80%E5%90%8E%E4%B8%80%E8%A1%8C%E4%B8%8D%E8%83%BD%E5%B7%A6%E5%AF%B9%E9%BD%90.html"
  },
  {
    name: "v-439fb3dc",
    path: "/posts/uniapp%E5%90%84%E7%AB%AF%E5%B7%AE%E5%BC%82.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-439fb3dc").then(next)
    },
  },
  {
    path: "/posts/uniapp各端差异.html",
    redirect: "/posts/uniapp%E5%90%84%E7%AB%AF%E5%B7%AE%E5%BC%82.html"
  },
  {
    path: "/posts/uniapp各端差异.html",
    redirect: "/posts/uniapp%E5%90%84%E7%AB%AF%E5%B7%AE%E5%BC%82.html"
  },
  {
    name: "v-5aac5935",
    path: "/posts/uniapp%E7%BC%96%E8%AF%91%E6%88%90%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%88%B0%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5aac5935").then(next)
    },
  },
  {
    path: "/posts/uniapp编译成小程序访问不到组件.html",
    redirect: "/posts/uniapp%E7%BC%96%E8%AF%91%E6%88%90%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%88%B0%E7%BB%84%E4%BB%B6.html"
  },
  {
    path: "/posts/uniapp编译成小程序访问不到组件.html",
    redirect: "/posts/uniapp%E7%BC%96%E8%AF%91%E6%88%90%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%88%B0%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-1c8102b0",
    path: "/posts/vant%E7%82%B9%E5%87%BB%E5%BC%B9%E5%87%BA%E6%A1%86%E5%86%8D%E8%B0%83%E5%8F%96%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c8102b0").then(next)
    },
  },
  {
    path: "/posts/vant点击弹出框再调取上传文件组件.html",
    redirect: "/posts/vant%E7%82%B9%E5%87%BB%E5%BC%B9%E5%87%BA%E6%A1%86%E5%86%8D%E8%B0%83%E5%8F%96%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E7%BB%84%E4%BB%B6.html"
  },
  {
    path: "/posts/vant点击弹出框再调取上传文件组件.html",
    redirect: "/posts/vant%E7%82%B9%E5%87%BB%E5%BC%B9%E5%87%BA%E6%A1%86%E5%86%8D%E8%B0%83%E5%8F%96%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-f6760794",
    path: "/posts/%E5%88%A4%E6%96%ADurl%E5%9B%BE%E7%89%87%E6%98%AF%E5%90%A6404.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f6760794").then(next)
    },
  },
  {
    path: "/posts/判断url图片是否404.html",
    redirect: "/posts/%E5%88%A4%E6%96%ADurl%E5%9B%BE%E7%89%87%E6%98%AF%E5%90%A6404.html"
  },
  {
    path: "/posts/判断url图片是否404.html",
    redirect: "/posts/%E5%88%A4%E6%96%ADurl%E5%9B%BE%E7%89%87%E6%98%AF%E5%90%A6404.html"
  },
  {
    name: "v-74b6e4c0",
    path: "/posts/%E6%A2%AF%E5%BD%A2%E6%96%9C%E8%BE%B9%E5%BC%A7%E5%BA%A6tab_css%E5%AE%9E%E7%8E%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74b6e4c0").then(next)
    },
  },
  {
    path: "/posts/梯形斜边弧度tab_css实现.html",
    redirect: "/posts/%E6%A2%AF%E5%BD%A2%E6%96%9C%E8%BE%B9%E5%BC%A7%E5%BA%A6tab_css%E5%AE%9E%E7%8E%B0.html"
  },
  {
    path: "/posts/梯形斜边弧度tab_css实现.html",
    redirect: "/posts/%E6%A2%AF%E5%BD%A2%E6%96%9C%E8%BE%B9%E5%BC%A7%E5%BA%A6tab_css%E5%AE%9E%E7%8E%B0.html"
  },
  {
    name: "v-3b0db29e",
    path: "/posts/%E5%AE%9D%E5%A1%94pm2%E9%83%A8%E7%BD%B2node%E7%9A%84%E5%9D%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b0db29e").then(next)
    },
  },
  {
    path: "/posts/宝塔pm2部署node的坑.html",
    redirect: "/posts/%E5%AE%9D%E5%A1%94pm2%E9%83%A8%E7%BD%B2node%E7%9A%84%E5%9D%91.html"
  },
  {
    path: "/posts/宝塔pm2部署node的坑.html",
    redirect: "/posts/%E5%AE%9D%E5%A1%94pm2%E9%83%A8%E7%BD%B2node%E7%9A%84%E5%9D%91.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]