/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "lzx博客",
  "description": "哈哈哈哈哈哈哈",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpg",
        "actionText": "快速进入→",
        "actionLink": "/posts/uniapp.html",
        "features": [
          {
            "title": "First",
            "details": "做好自己"
          },
          {
            "title": "Second",
            "details": "享受生活"
          },
          {
            "title": "Third",
            "details": "提升未来"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2021-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-bc09bd4c",
      "path": "/",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "左右拉动组件",
      "frontmatter": {},
      "regularPath": "/components/%E5%B7%A6%E5%8F%B3%E6%8B%89%E5%8A%A8%E7%BB%84%E4%BB%B6.html",
      "relativePath": "components/左右拉动组件.md",
      "key": "v-3fdbf9de",
      "path": "/components/%E5%B7%A6%E5%8F%B3%E6%8B%89%E5%8A%A8%E7%BB%84%E4%BB%B6.html",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "ES6 常用语法",
      "frontmatter": {},
      "regularPath": "/posts/ES6%20%E5%B8%B8%E7%94%A8%E8%AF%AD%E6%B3%95.html",
      "relativePath": "posts/ES6 常用语法.md",
      "key": "v-609aeb54",
      "path": "/posts/ES6%20%E5%B8%B8%E7%94%A8%E8%AF%AD%E6%B3%95.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是ES6",
          "slug": "什么是es6"
        },
        {
          "level": 2,
          "title": "1.解构赋值",
          "slug": "_1-解构赋值"
        },
        {
          "level": 2,
          "title": "2.Map和Set",
          "slug": "_2-map和set"
        },
        {
          "level": 3,
          "title": "Map 对象",
          "slug": "map-对象"
        },
        {
          "level": 3,
          "title": "Set 对象",
          "slug": "set-对象"
        },
        {
          "level": 2,
          "title": "3.字符串、对象、数组和函数",
          "slug": "_3-字符串、对象、数组和函数"
        },
        {
          "level": 3,
          "title": "字符串",
          "slug": "字符串-2"
        },
        {
          "level": 3,
          "title": "对象",
          "slug": "对象"
        },
        {
          "level": 3,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 3,
          "title": "函数",
          "slug": "函数"
        },
        {
          "level": 2,
          "title": "4.Reflect与Proxy",
          "slug": "_4-reflect与proxy"
        },
        {
          "level": 3,
          "title": "Proxy",
          "slug": "proxy"
        },
        {
          "level": 3,
          "title": "Reflect",
          "slug": "reflect"
        },
        {
          "level": 3,
          "title": "组合使用",
          "slug": "组合使用"
        },
        {
          "level": 2,
          "title": "5.Promise",
          "slug": "_5-promise"
        },
        {
          "level": 3,
          "title": "Promise 状态",
          "slug": "promise-状态"
        },
        {
          "level": 3,
          "title": "then 方法",
          "slug": "then-方法"
        },
        {
          "level": 3,
          "title": "Promise封装axios",
          "slug": "promise封装axios"
        },
        {
          "level": 3,
          "title": "Promise.prototype.catch方法：捕捉错误",
          "slug": "promise-prototype-catch方法-捕捉错误"
        },
        {
          "level": 3,
          "title": "Promise.all方法，Promise.race方法",
          "slug": "promise-all方法-promise-race方法"
        },
        {
          "level": 2,
          "title": "6.Generator函数和async函数",
          "slug": "_6-generator函数和async函数"
        },
        {
          "level": 3,
          "title": "Generator 函数组成",
          "slug": "generator-函数组成"
        },
        {
          "level": 3,
          "title": "执行机制",
          "slug": "执行机制"
        },
        {
          "level": 3,
          "title": "async函数",
          "slug": "async函数"
        }
      ],
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "Vue组件的通信总结",
      "frontmatter": {
        "title": "Vue组件的通信总结",
        "date": "2020-03-10T00:00:00.000Z",
        "tags": [
          "vue组件"
        ],
        "categories": [
          "vue"
        ]
      },
      "regularPath": "/posts/121501.html",
      "relativePath": "posts/121501.md",
      "key": "v-98bb5b48",
      "path": "/posts/121501.html",
      "headers": [
        {
          "level": 2,
          "title": "1、props/$emit",
          "slug": "_1、props-emit"
        },
        {
          "level": 2,
          "title": "2、 eventBus事件总线 $emit/$on",
          "slug": "_2、-eventbus事件总线-emit-on"
        },
        {
          "level": 2,
          "title": "3、 provide / inject",
          "slug": "_3、-provide-inject"
        },
        {
          "level": 2,
          "title": "4、 $parent / $children",
          "slug": "_4、-parent-children"
        },
        {
          "level": 2,
          "title": "5、 $root & refs",
          "slug": "_5、-root-refs"
        },
        {
          "level": 2,
          "title": "6、 Vuex",
          "slug": "_6、-vuex"
        }
      ],
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "ajax返回blob封装",
      "frontmatter": {},
      "regularPath": "/posts/ajax%E8%BF%94%E5%9B%9Eblob%E5%B0%81%E8%A3%85.html",
      "relativePath": "posts/ajax返回blob封装.md",
      "key": "v-16132974",
      "path": "/posts/ajax%E8%BF%94%E5%9B%9Eblob%E5%B0%81%E8%A3%85.html",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "footer位置的自动适配",
      "frontmatter": {},
      "regularPath": "/posts/footer%E4%BD%8D%E7%BD%AE%E7%9A%84%E8%87%AA%E5%8A%A8%E9%80%82%E9%85%8D.html",
      "relativePath": "posts/footer位置的自动适配.md",
      "key": "v-c069814e",
      "path": "/posts/footer%E4%BD%8D%E7%BD%AE%E7%9A%84%E8%87%AA%E5%8A%A8%E9%80%82%E9%85%8D.html",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "uniapp",
      "frontmatter": {},
      "regularPath": "/posts/uniapp.html",
      "relativePath": "posts/uniapp.md",
      "key": "v-0a1dfd74",
      "path": "/posts/uniapp.html",
      "headers": [
        {
          "level": 2,
          "title": "准备过程",
          "slug": "准备过程"
        },
        {
          "level": 2,
          "title": "1.   下载HBuilder X（开发使用）和微信开发者工具（预览使用）",
          "slug": "_1-下载hbuilder-x-开发使用-和微信开发者工具-预览使用"
        },
        {
          "level": 2,
          "title": "2.   导入uniapp项目，安装依赖并安装本地运行需要的插件，在HBuilderX的工具->插件安装",
          "slug": "_2-导入uniapp项目-安装依赖并安装本地运行需要的插件-在hbuilderx的工具-插件安装"
        },
        {
          "level": 2,
          "title": "3.\t在manifest.json的微信小程序配置中填写自己的微信小程序AppID",
          "slug": "_3-在manifest-json的微信小程序配置中填写自己的微信小程序appid"
        },
        {
          "level": 2,
          "title": "4.\t运行->运行到小程序模拟器即可",
          "slug": "_4-运行-运行到小程序模拟器即可"
        },
        {
          "level": 2,
          "title": "开发",
          "slug": "开发"
        }
      ],
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "space-around最后一行不能左对齐",
      "frontmatter": {},
      "regularPath": "/posts/space-around%E6%9C%80%E5%90%8E%E4%B8%80%E8%A1%8C%E4%B8%8D%E8%83%BD%E5%B7%A6%E5%AF%B9%E9%BD%90.html",
      "relativePath": "posts/space-around最后一行不能左对齐.md",
      "key": "v-7ab37238",
      "path": "/posts/space-around%E6%9C%80%E5%90%8E%E4%B8%80%E8%A1%8C%E4%B8%8D%E8%83%BD%E5%B7%A6%E5%AF%B9%E9%BD%90.html",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "Vue uniapp各端差异",
      "frontmatter": {},
      "regularPath": "/posts/uniapp%E5%90%84%E7%AB%AF%E5%B7%AE%E5%BC%82.html",
      "relativePath": "posts/uniapp各端差异.md",
      "key": "v-439fb3dc",
      "path": "/posts/uniapp%E5%90%84%E7%AB%AF%E5%B7%AE%E5%BC%82.html",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "uniapp编译成小程序访问不到组件",
      "frontmatter": {},
      "regularPath": "/posts/uniapp%E7%BC%96%E8%AF%91%E6%88%90%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%88%B0%E7%BB%84%E4%BB%B6.html",
      "relativePath": "posts/uniapp编译成小程序访问不到组件.md",
      "key": "v-5aac5935",
      "path": "/posts/uniapp%E7%BC%96%E8%AF%91%E6%88%90%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%88%B0%E7%BB%84%E4%BB%B6.html",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "Vant：点击弹出框再调取上传文件组件",
      "frontmatter": {},
      "regularPath": "/posts/vant%E7%82%B9%E5%87%BB%E5%BC%B9%E5%87%BA%E6%A1%86%E5%86%8D%E8%B0%83%E5%8F%96%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E7%BB%84%E4%BB%B6.html",
      "relativePath": "posts/vant点击弹出框再调取上传文件组件.md",
      "key": "v-1c8102b0",
      "path": "/posts/vant%E7%82%B9%E5%87%BB%E5%BC%B9%E5%87%BA%E6%A1%86%E5%86%8D%E8%B0%83%E5%8F%96%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E7%BB%84%E4%BB%B6.html",
      "headers": [
        {
          "level": 2,
          "title": "问题描述",
          "slug": "问题描述"
        }
      ],
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "判断url图片是否404",
      "frontmatter": {},
      "regularPath": "/posts/%E5%88%A4%E6%96%ADurl%E5%9B%BE%E7%89%87%E6%98%AF%E5%90%A6404.html",
      "relativePath": "posts/判断url图片是否404.md",
      "key": "v-f6760794",
      "path": "/posts/%E5%88%A4%E6%96%ADurl%E5%9B%BE%E7%89%87%E6%98%AF%E5%90%A6404.html",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "title": "梯形斜边弧度tab_css实现",
      "frontmatter": {},
      "regularPath": "/posts/%E6%A2%AF%E5%BD%A2%E6%96%9C%E8%BE%B9%E5%BC%A7%E5%BA%A6tab_css%E5%AE%9E%E7%8E%B0.html",
      "relativePath": "posts/梯形斜边弧度tab_css实现.md",
      "key": "v-74b6e4c0",
      "path": "/posts/%E6%A2%AF%E5%BD%A2%E6%96%9C%E8%BE%B9%E5%BC%A7%E5%BA%A6tab_css%E5%AE%9E%E7%8E%B0.html",
      "lastUpdated": "4/28/2021, 11:08:26 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/posts/%E5%AE%9D%E5%A1%94pm2%E9%83%A8%E7%BD%B2node%E7%9A%84%E5%9D%91.html",
      "relativePath": "posts/宝塔pm2部署node的坑.md",
      "key": "v-3b0db29e",
      "path": "/posts/%E5%AE%9D%E5%A1%94pm2%E9%83%A8%E7%BD%B2node%E7%9A%84%E5%9D%91.html"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "我的博客",
        "link": "/posts/uniapp"
      },
      {
        "text": "我的组件",
        "link": "/components/左右拉动组件"
      },
      {
        "text": "GitHub",
        "items": [
          {
            "text": "GitHub地址",
            "link": "https://github.com/hndd99cla"
          }
        ]
      }
    ],
    "sidebar": {
      "/posts/": [
        {
          "title": "uniapp",
          "children": [
            "/posts/uniapp",
            "/posts/uniapp编译成小程序访问不到组件",
            "/posts/uniapp各端差异"
          ]
        },
        {
          "title": "css",
          "children": [
            "/posts/梯形斜边弧度tab_css实现",
            "/posts/footer位置的自动适配"
          ]
        },
        {
          "title": "js",
          "children": [
            "/posts/ES6 常用语法",
            "/posts/121501",
            "/posts/判断url图片是否404",
            "/posts/ajax返回blob封装"
          ]
        },
        {
          "title": "node",
          "children": [
            "/posts/宝塔pm2部署node的坑"
          ]
        }
      ],
      "/components/": [
        {
          "title": "我的组件",
          "children": [
            "/components/左右拉动组件"
          ]
        }
      ]
    }
  }
}